# Generated by Django 4.0.5 on 2022-06-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0002_alter_restaurant_description_alter_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, max_length=10009, null=True),
        ),
    ]
