# Generated by Django 4.0.5 on 2022-06-29 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0003_alter_restaurant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=59, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('restaurants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_comments', to='eatery.restaurant')),
            ],
        ),
    ]
